sudo: required
services: 
  - docker

before_install:
  - docker build -t santicarta/docker-react -f Dockerfile.dev .

script:
  - docker run santicarta/docker-react npm run test -- App.test.js --coverage